# Generated by Django 3.2.4 on 2021-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('aadhar', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=20)),
                ('picture', models.ImageField(default='', upload_to='static/profile')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('rdate', models.DateField()),
                ('passwd', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
