# Generated by Django 3.2.4 on 2021-09-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='rdate',
        ),
    ]
