# Generated by Django 3.2.4 on 2021-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_signup_rdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingelction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=100)),
                ('edes', models.TextField(max_length=5000)),
                ('edate', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
