# Generated by Django 3.2.4 on 2021-10-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_upcomingelction'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=20)),
                ('vparty', models.CharField(max_length=20)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
